# Generated by Django 4.2 on 2023-04-07 12:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_post_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_upload',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
