# Generated by Django 4.2 on 2023-04-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_app', '0004_category_post_create_time_userpost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='User',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='responses',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.AddField(
            model_name='responses',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.post'),
        ),
    ]
