# Generated by Django 4.2 on 2023-04-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_onetimecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
